services:

  mysql:
    image: mysql:8.0
    container_name: blog-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb

    ports:
      - "3306:3306"

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build: ./backend

    container_name: blog-flask

    ports:
      - "5000:5000"

    depends_on:
      - mysql
